openapi: 3.0.3
info:
  version: 1.0.0
  title: Team API
  description: Team api 
  x-sla:
    $ref: ./plans.yaml
security:
  - BearerAuth: []
paths:
  /api/v1/foses:
    x-router-controller: fosesController
    get:
      description: Returns all teams
      operationId: getFosess
      responses:
        200:
          description: foses list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/foses'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  
                  
  /api/v1/foses/{Id}:
    x-router-controller: fosesController
    get:
      description: Returns a single team by its id
      operationId: findById
      parameters:
        - required: true
          name: Id
          description: id of the foses to fetch
          in: path
          schema:
            type: number
      responses:
        200:
          description: Team found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foses'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    foses:
        type: object
        required:
          - Id
        properties:
          Id:
            type: number
          title:
            type: string
          province:
            type: string
          municipality:
            type: string
          dateNumeric:
            type: number
          victims:
            type: number
          dates_act:
            type: number
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true